### ISSUE TITLE
Won't retry if API returns 503 "Service Unavailable"

### ISSUE THREAD

**Issue by josemdv** [taers232c/GAMADV-X#1]
First of all thank you for making this awesome version of GAM. 

I'm facing some issues using the Calendar API. I administer a domain that has more than 5K users and every single day I need to delete some terminated employees from all the "Contacts" API for every single user. 

I'm running the following command:

gam all users info/delete contact query terminated-employee@domain.com

After a few thousand queries, the API returns "Service Unavailable" that only last for 1-2 seconds. 

This brakes the functionality of this command as it doesn't retry again after a failure. 

I need to run the command again and hope that the API doesn't return a 503 for the next 50-60 (time that it takes to search for a single contact for all our users). 

I attached an example.

Thanks!

`Got 0 Contacts...
User: axyz1@domain.com, Show Info 0 Contacts (222/5246)
Getting all Contacts that match query (user1@domain.com) for xxxxx@domain.com (223/5246)
Got 0 Contacts...
User: bxyz1@domain.com, Show Info 0 Contacts (223/5246)
Getting all Contacts that match query (userx@domain.com) for xxxxx@domain.com (224/5246)

ERROR: 600 - Unknown Error: {'status': 503, 'body': '<?xml version="1.0" encoding="UTF-8"?>\n<errors xmlns="http://schem
as.google.com/g/2005">\n <error>\n  <domain>GData</domain>\n  <code>backendError</code>\n  <internalReason>Backend Error
</internalReason>\n </error>\n</errors>\n', 'reason': 'Service Unavailable'}`

**Comment by taers232c** [comment]
Yikes! Does the computer smoke while you're doing this?

I see what the problem is, I'll try to duplicate the problem here but the
number of users I have is about 500 although in your case it died earlier
than that.

Ross



On Wed, Jun 29, 2016 at 1:58 PM, Just my stuff <notifications@github.com>
wrote:

> First of all thank you for making this awesome version of GAM.
>
> I'm facing some issues using the Calendar API. I administer a domain that
> has more than 5K users and every single day I need to delete some
> terminated employees from all the "Contacts" API for every single user.
>
> I'm running the following command:
>
> gam all users info/delete contact query terminated-employee@domain.com
>
> After a few thousand queries, the API returns "Service Unavailable" that
> only last for 1-2 seconds.
>
> This brakes the functionality of this command as it doesn't retry again
> after a failure.
>
> I need to run the command again and hope that the API doesn't return a 503
> for the next 50-60 (time that it takes to search for a single contact for
> all our users).
>
> I attached an example.
>
> Thanks!
>
> `Got 0 Contacts...
> User: axyz1@domain.com, Show Info 0 Contacts (222/5246)
> Getting all Contacts that match query (user1@domain.com) for
> xxxxx@domain.com (223/5246)
> Got 0 Contacts...
> User: bxyz1@domain.com, Show Info 0 Contacts (223/5246)
> Getting all Contacts that match query (userx@domain.com) for
> xxxxx@domain.com (224/5246)
>
> ERROR: 600 - Unknown Error: {'status': 503, 'body': '<?xml version="1.0"
> encoding="UTF-8"?>\n\n \n GData\n backendError\n Backend Error
> \n \n\n', 'reason': 'Service Unavailable'}`
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/taers232c/GAMADV-X/issues/1>, or mute the thread
> <https://github.com/notifications/unsubscribe/AIU8L1gP8JFQvui1hCAw7mdk7PZ04WBxks5qQtyEgaJpZM4JBjx0>
> .
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
I've added a check for the error, try this:
<https://github.com/taers232c/GAMADV-X/releases/tag/v4.16.4>
https://github.com/taers232c/GAMADV-X/releases/tag/v4.16.4
<https://github.com/taers232c/GAMADV-X/releases/tag/v4.16.4>

See GamUpdates.txt, I've added support for user Contact Groups, Google
Sites and showing users messages/threads.

Ross

On Wed, Jun 29, 2016 at 2:32 PM, Ross Scroggs <ross.scroggs@gmail.com>
wrote:

> Yikes! Does the computer smoke while you're doing this?
>
> I see what the problem is, I'll try to duplicate the problem here but the
> number of users I have is about 500 although in your case it died earlier
> than that.
>
> Ross
>
>
>
> On Wed, Jun 29, 2016 at 1:58 PM, Just my stuff <notifications@github.com>
> wrote:
>
>> First of all thank you for making this awesome version of GAM.
>>
>> I'm facing some issues using the Calendar API. I administer a domain that
>> has more than 5K users and every single day I need to delete some
>> terminated employees from all the "Contacts" API for every single user.
>>
>> I'm running the following command:
>>
>> gam all users info/delete contact query terminated-employee@domain.com
>>
>> After a few thousand queries, the API returns "Service Unavailable" that
>> only last for 1-2 seconds.
>>
>> This brakes the functionality of this command as it doesn't retry again
>> after a failure.
>>
>> I need to run the command again and hope that the API doesn't return a
>> 503 for the next 50-60 (time that it takes to search for a single contact
>> for all our users).
>>
>> I attached an example.
>>
>> Thanks!
>>
>> `Got 0 Contacts...
>> User: axyz1@domain.com, Show Info 0 Contacts (222/5246)
>> Getting all Contacts that match query (user1@domain.com) for
>> xxxxx@domain.com (223/5246)
>> Got 0 Contacts...
>> User: bxyz1@domain.com, Show Info 0 Contacts (223/5246)
>> Getting all Contacts that match query (userx@domain.com) for
>> xxxxx@domain.com (224/5246)
>>
>> ERROR: 600 - Unknown Error: {'status': 503, 'body': '<?xml version="1.0"
>> encoding="UTF-8"?>\n\n \n GData\n backendError\n Backend Error
>> \n \n\n', 'reason': 'Service Unavailable'}`
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/taers232c/GAMADV-X/issues/1>, or mute the thread
>> <https://github.com/notifications/unsubscribe/AIU8L1gP8JFQvui1hCAw7mdk7PZ04WBxks5qQtyEgaJpZM4JBjx0>
>> .
>>
>
>
>
> --
> Ross Scroggs
> ross.scroggs@gmail.com
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by josemdv** [comment]
Hi Ross,

Thank you so much!!

I update to the latest version (V4.16.4) and now I got this error few minutes after I ran the same query:

It seems that when it fails, it starts from the beginning rather than just keep retrying the same user/query.  



Getting all Contacts that match query (user@domain.com) for user@domain.com (83/5257)
Got 0 Contacts...
User: user@domain.com, Show Info 0 Contacts (83/5257)
Getting all Contacts that match query (user@domain.com) for user@domain.com (84/5257)
ERROR: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Getting all Users, may take some time on a large Account...
Got 5521 Users...
Got 5257 Users
Getting all Contacts that match query (user@domain.com) for user@domain.com (1/5257)
Got 0 Contacts... 




Another example:







Got 0 Contacts...
User: user@domain.com, Show Info 0 Contacts (16/5256)
Getting all Contacts that match query (user@domain.com) for user@domain.com (17/5256)
Got 0 Contacts...
User: user@domain.com, Show Info 0 Contacts (17/5256)
Getting all Contacts that match query (user@domain.com) for user@domain.com (18/5256)

ERROR: 600 - Unknown Error: {'status': 500, 'body': '<?xml version="1.0" encoding="UTF-8"?>\n<errors xmlns="http://schem
as.google.com/g/2005">\n <error>\n  <domain>GData</domain>\n  <code>internalError</code>\n  <internalReason>Internal Err
or</internalReason>\n </error>\n</errors>\n', 'reason': 'Internal Server Error'}
Getting all Users, may take some time on a large Account...
Got 5521 Users...
Got 5257 Users

**Comment by taers232c** [comment]
You output does not match what I expect. Can you give me the actual command
you enter and more of the output.
This is what I expect:

$ gam  all users  info contact query XXXXX

Getting all Users, may take some time on a large Account...

Got 564 Users...

Got 530 Users

Getting all Contacts that match query (XXXXX) for
4thgradesubjob2016@rdschool.org (1/530)

Got 0 Contacts...

User: 4thgradesubjob2016@rdschool.org, Show Info 0 Contacts (1/530)

Getting all Contacts that match query (XXXXX) for aadefela@rdschool.org
(2/530)


If we get that error, it should only be retrying the query for the current
user, it should not be going back to Getting all users, ...


I see that I need to trap the Internal server error as well.


Do: gam config verify

What's the value of auto_batch_min?


Refresh from here:
https://github.com/taers232c/GAMADV-X/releases/tag/v4.16.4


Ross

On Wed, Jun 29, 2016 at 4:13 PM, Just my stuff <notifications@github.com>
wrote:

> Hi Ross,
>
> Thank you so much!!
>
> I update to the latest version (V4.16.4) and now I got this error few
> minutes after I ran the same query:
>
> It seems that when it fails, it starts from the beginning rather than just
> keep retrying the same user/query.
>
> Getting all Contacts that match query (user@domain.com) for
> user@domain.com (83/5257)
> Got 0 Contacts...
> User: user@domain.com, Show Info 0 Contacts (83/5257)
> Getting all Contacts that match query (user@domain.com) for
> user@domain.com (84/5257)
> ERROR: A connection attempt failed because the connected party did not
> properly respond after a period of time, or established connection failed
> because connected host has failed to respond
> Getting all Users, may take some time on a large Account...
> Got 5521 Users...
> Got 5257 Users
> Getting all Contacts that match query (user@domain.com) for
> user@domain.com (1/5257)
> Got 0 Contacts...
>
> Another example:
>
> Got 0 Contacts...
> User: user@domain.com, Show Info 0 Contacts (16/5256)
> Getting all Contacts that match query (user@domain.com) for
> user@domain.com (17/5256)
> Got 0 Contacts...
> User: user@domain.com, Show Info 0 Contacts (17/5256)
> Getting all Contacts that match query (user@domain.com) for
> user@domain.com (18/5256)
>
> ERROR: 600 - Unknown Error: {'status': 500, 'body': '<?xml version="1.0"
> encoding="UTF-8"?>\n\n \n GData\n internalError\n Internal Err
> or\n \n\n', 'reason': 'Internal Server Error'}
> Getting all Users, may take some time on a large Account...
> Got 5521 Users...
> Got 5257 Users
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229517065>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIU8L3xs5s1xl5plGAqX3JnxU6zD9jtxks5qQvwFgaJpZM4JBjx0>
> .
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
I fixed a couple of other issues, version rolled:
https://github.com/taers232c/GAMADV-X/releases/tag/v4.16.5

Ross

On Wed, Jun 29, 2016 at 5:03 PM, Ross Scroggs <ross.scroggs@gmail.com>
wrote:

> You output does not match what I expect. Can you give me the actual
> command you enter and more of the output.
> This is what I expect:
>
> $ gam  all users  info contact query XXXXX
>
> Getting all Users, may take some time on a large Account...
>
> Got 564 Users...
>
> Got 530 Users
>
> Getting all Contacts that match query (XXXXX) for
> 4thgradesubjob2016@rdschool.org (1/530)
>
> Got 0 Contacts...
>
> User: 4thgradesubjob2016@rdschool.org, Show Info 0 Contacts (1/530)
>
> Getting all Contacts that match query (XXXXX) for aadefela@rdschool.org
> (2/530)
>
>
> If we get that error, it should only be retrying the query for the current
> user, it should not be going back to Getting all users, ...
>
>
> I see that I need to trap the Internal server error as well.
>
>
> Do: gam config verify
>
> What's the value of auto_batch_min?
>
>
> Refresh from here:
> https://github.com/taers232c/GAMADV-X/releases/tag/v4.16.4
>
>
> Ross
>
> On Wed, Jun 29, 2016 at 4:13 PM, Just my stuff <notifications@github.com>
> wrote:
>
>> Hi Ross,
>>
>> Thank you so much!!
>>
>> I update to the latest version (V4.16.4) and now I got this error few
>> minutes after I ran the same query:
>>
>> It seems that when it fails, it starts from the beginning rather than
>> just keep retrying the same user/query.
>>
>> Getting all Contacts that match query (user@domain.com) for
>> user@domain.com (83/5257)
>> Got 0 Contacts...
>> User: user@domain.com, Show Info 0 Contacts (83/5257)
>> Getting all Contacts that match query (user@domain.com) for
>> user@domain.com (84/5257)
>> ERROR: A connection attempt failed because the connected party did not
>> properly respond after a period of time, or established connection failed
>> because connected host has failed to respond
>> Getting all Users, may take some time on a large Account...
>> Got 5521 Users...
>> Got 5257 Users
>> Getting all Contacts that match query (user@domain.com) for
>> user@domain.com (1/5257)
>> Got 0 Contacts...
>>
>> Another example:
>>
>> Got 0 Contacts...
>> User: user@domain.com, Show Info 0 Contacts (16/5256)
>> Getting all Contacts that match query (user@domain.com) for
>> user@domain.com (17/5256)
>> Got 0 Contacts...
>> User: user@domain.com, Show Info 0 Contacts (17/5256)
>> Getting all Contacts that match query (user@domain.com) for
>> user@domain.com (18/5256)
>>
>> ERROR: 600 - Unknown Error: {'status': 500, 'body': '<?xml version="1.0"
>> encoding="UTF-8"?>\n\n \n GData\n internalError\n Internal Err
>> or\n \n\n', 'reason': 'Internal Server Error'}
>> Getting all Users, may take some time on a large Account...
>> Got 5521 Users...
>> Got 5257 Users
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229517065>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AIU8L3xs5s1xl5plGAqX3JnxU6zD9jtxks5qQvwFgaJpZM4JBjx0>
>> .
>>
>
>
>
> --
> Ross Scroggs
> ross.scroggs@gmail.com
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Grab the latest: https://github.com/taers232c/GAMADV-X/releases/tag/v4.16.6

Run again, grab the output, let me know what happens.

Ross
--
ross.scroggs@gmail.com

**Comment by josemdv** [comment]
Hi Ross,

I tried to reproduce the same issue with the v4.16.5 during more than 10 hours without issues at all. 

I'll keep you posted.
Thanks!!

**Comment by taers232c** [comment]
There should be an error message saying that Gam is retrying; do you see
any of those? If so, send me an example.

Ross

On Thu, Jun 30, 2016 at 11:12 AM, Just my stuff <notifications@github.com>
wrote:

> Hi Ross,
>
> I tried to reproduce the same issue with the v4.16.5 during more than 10
> hours without issues at all.
>
> I'll keep you posted.
> Thanks!!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229742849>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIU8LxohckcPKmhn7Sde8B3dIvgM8AvUks5qRAcXgaJpZM4JBjx0>
> .
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Rapid changes in the print/show messages area, at your convenience, upgrade
to: https://github.com/taers232c/GAMADV-X/releases/tag/v4.17.0

Of course, this includes the fixes relating the info contacts problems.

Try: gam user foo@bar.com show messages
Or: gam user foo@bar.com print messages

Ross

On Thu, Jun 30, 2016 at 11:20 AM, Ross Scroggs <ross.scroggs@gmail.com>
wrote:

> There should be an error message saying that Gam is retrying; do you see
> any of those? If so, send me an example.
>
> Ross
>
> On Thu, Jun 30, 2016 at 11:12 AM, Just my stuff <notifications@github.com>
> wrote:
>
>> Hi Ross,
>>
>> I tried to reproduce the same issue with the v4.16.5 during more than 10
>> hours without issues at all.
>>
>> I'll keep you posted.
>> Thanks!!
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229742849>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AIU8LxohckcPKmhn7Sde8B3dIvgM8AvUks5qRAcXgaJpZM4JBjx0>
>> .
>>
>
>
>
> --
> Ross Scroggs
> ross.scroggs@gmail.com
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by josemdv** [comment]
Updated to the latest version and I just now ran into a different error.



Getting all Contacts that match query (athieme@domain.com) for nasimb@domain.com (3772/5265)
Got 0 Contacts...
Getting all Contacts that match query (athieme@domain.com) for nataliap@domain.com (3773/5265)
Got 0 Contacts...
Getting all Contacts that match query (athieme@domain.com) for nataliea@domain.com (3774/5265)
Got 0 Contacts...
Getting all Contacts that match query (athieme@domain.com) for nataliem@domain.com (3775/5265)
Got 0 Contacts...
Getting all Contacts that match query (athieme@domain.com) for natalien@domain.com (3776/5265)
Got 0 Contacts...
Getting all Contacts that match query (athieme@domain.com) for natalier@domain.com (3777/5265)
Got 0 Contacts...
Getting all Contacts that match query (athieme@domain.com) for natars@domain.com (3778/5265)
Got 0 Contacts...
Getting all Contacts that match query (athieme@domain.com) for nate@domain.com (3779/5265)
Got 0 Contacts...
Getting all Contacts that match query (athieme@domain.com) for nathanb@domain.com (3780/5265)
Got 0 Contacts...
Getting all Contacts that match query (athieme@domain.com) for nathanf@domain.com (3781/5265)

ERROR: 600 - Unknown Error: {'status': 403, 'body': '<?xml version="1.0" encoding="UTF-8"?>\n<errors xmlns="http://schem
as.google.com/g/2005">\n <error>\n  <domain>GData</domain>\n  <code>forbidden</code>\n  <internalReason>Cannot request contacts belonging to another user</internalReason>\n </error>\n</errors>\n', 'reason': 'Forbidden'}


And the GAM returns to the main powershell window and exits.

**Comment by taers232c** [comment]
What's different about the last user shown?

I can trap the error but I wonder what's going on.

Do that user by hand, do you always get the error?

Ross


On Thu, Jun 30, 2016 at 3:00 PM, Just my stuff <notifications@github.com>
wrote:

> Updated to the latest version and I just now ran into a different error.
>
> Getting all Contacts that match query (athieme@domain.com) for
> nasimb@domain.com (3772/5265)
> Got 0 Contacts...
> Getting all Contacts that match query (athieme@domain.com) for
> nataliap@domain.com (3773/5265)
> Got 0 Contacts...
> Getting all Contacts that match query (athieme@domain.com) for
> nataliea@domain.com (3774/5265)
> Got 0 Contacts...
> Getting all Contacts that match query (athieme@domain.com) for
> nataliem@domain.com (3775/5265)
> Got 0 Contacts...
> Getting all Contacts that match query (athieme@domain.com) for
> natalien@domain.com (3776/5265)
> Got 0 Contacts...
> Getting all Contacts that match query (athieme@domain.com) for
> natalier@domain.com (3777/5265)
> Got 0 Contacts...
> Getting all Contacts that match query (athieme@domain.com) for
> natars@domain.com (3778/5265)
> Got 0 Contacts...
> Getting all Contacts that match query (athieme@domain.com) for
> nate@domain.com (3779/5265)
> Got 0 Contacts...
> Getting all Contacts that match query (athieme@domain.com) for
> nathanb@domain.com (3780/5265)
> Got 0 Contacts...
> Getting all Contacts that match query (athieme@domain.com) for
> nathanf@domain.com (3781/5265)
>
> ERROR: 600 - Unknown Error: {'status': 403, 'body': '<?xml version="1.0"
> encoding="UTF-8"?>\n\n \n GData\n forbidden\n Cannot request contacts
> belonging to another user\n \n\n', 'reason': 'Forbidden'}
>
> And the GAM returns to the main powershell window and exits.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229801357>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIU8L-ZSF9rFsCqrEgZU3RlZzU-uUuljks5qRDx3gaJpZM4JBjx0>
> .
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
It's because the last name shown is an alias.

The Contacts API 'Don't like no stinking aliases'

Fix in works.

Ross

On Thu, Jun 30, 2016 at 3:11 PM, Ross Scroggs <ross.scroggs@gmail.com>
wrote:

>
> What's different about the last user shown?
>
> I can trap the error but I wonder what's going on.
>
> Do that user by hand, do you always get the error?
>
> Ross
>
>
> On Thu, Jun 30, 2016 at 3:00 PM, Just my stuff <notifications@github.com>
> wrote:
>
>> Updated to the latest version and I just now ran into a different error.
>>
>> Getting all Contacts that match query (athieme@domain.com) for
>> nasimb@domain.com (3772/5265)
>> Got 0 Contacts...
>> Getting all Contacts that match query (athieme@domain.com) for
>> nataliap@domain.com (3773/5265)
>> Got 0 Contacts...
>> Getting all Contacts that match query (athieme@domain.com) for
>> nataliea@domain.com (3774/5265)
>> Got 0 Contacts...
>> Getting all Contacts that match query (athieme@domain.com) for
>> nataliem@domain.com (3775/5265)
>> Got 0 Contacts...
>> Getting all Contacts that match query (athieme@domain.com) for
>> natalien@domain.com (3776/5265)
>> Got 0 Contacts...
>> Getting all Contacts that match query (athieme@domain.com) for
>> natalier@domain.com (3777/5265)
>> Got 0 Contacts...
>> Getting all Contacts that match query (athieme@domain.com) for
>> natars@domain.com (3778/5265)
>> Got 0 Contacts...
>> Getting all Contacts that match query (athieme@domain.com) for
>> nate@domain.com (3779/5265)
>> Got 0 Contacts...
>> Getting all Contacts that match query (athieme@domain.com) for
>> nathanb@domain.com (3780/5265)
>> Got 0 Contacts...
>> Getting all Contacts that match query (athieme@domain.com) for
>> nathanf@domain.com (3781/5265)
>>
>> ERROR: 600 - Unknown Error: {'status': 403, 'body': '<?xml version="1.0"
>> encoding="UTF-8"?>\n\n \n GData\n forbidden\n Cannot request contacts
>> belonging to another user\n \n\n', 'reason': 'Forbidden'}
>>
>> And the GAM returns to the main powershell window and exits.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229801357>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AIU8L-ZSF9rFsCqrEgZU3RlZzU-uUuljks5qRDx3gaJpZM4JBjx0>
>> .
>>
>
>
>
> --
> Ross Scroggs
> ross.scroggs@gmail.com
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by josemdv** [comment]
Hi Ross,

I always get the same error if I do it by hand. 

Your are right. If the user is an alias, then we get that 403.

**Comment by taers232c** [comment]
Handled: https://github.com/taers232c/GAMADV-X/releases/tag/v4.17.1
<https://github.com/taers232c/GAMADV-X/releases/tag/v4.17.1>

Ross

On Thu, Jun 30, 2016 at 3:25 PM, Just my stuff <notifications@github.com>
wrote:

> Hi Ross,
>
> I always get the same error if I do it by hand.
>
> Your are right. If the user is an alias, then we get that 403.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229806288>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIU8L8Po5BadfbtDTemwI4JiYb4Mk55Yks5qREJsgaJpZM4JBjx0>
> .
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by josemdv** [comment]
Thank you Ross,
Running GAM again, I'll keep you posted.

**Comment by taers232c** [comment]
I found a couple of unhanded cases with contactgroups, refresh at your
convenience: https://github.com/taers232c/GAMADV-X/releases/tag/v4.17.1

Thanks for your efforts in smoking out the problems,

Ross

On Thu, Jun 30, 2016 at 3:58 PM, Just my stuff <notifications@github.com>
wrote:

> Thank you Ross,
> Running GAM again, I'll keep you posted.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229812069>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIU8L77KTs2MJcPU6_FW7MaeD8fRUKCnks5qREoXgaJpZM4JBjx0>
> .
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by josemdv** [comment]
Thank you! Maybe this isn't related at all with this issue, but I found that increasing the number of batch runs from 10 to 20, doesn't have any effect. Running a query (delete a contact) for + 5K users is really time consuming. It takes up to one hour. I have to delete up to 20 contacts every day from all Google accounts. I tried also running several instance of GAM at the same time but there is some type of PID lock that doesn't let me run more than 2 instances at the same time.

**Comment by taers232c** [comment]
What values do you have for num_threads, no_cache and no_update_check?

On Thu, Jun 30, 2016 at 4:28 PM, Just my stuff <notifications@github.com>
wrote:

> Thank you! Maybe this isn't related at all with this issue, but I found
> that increasing the number of batch runs from 10 to 20, doesn't have any
> effect. Running a query (delete a contact) for + 5K users is really time
> consuming. It takes up to one hour. I have to delete up to 20 contacts
> every day from all Google accounts. I tried also running several instance
> of GAM at the same time but there is some type of PID lock that doesn't let
> me run more than 2 instances at the same time.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229816916>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIU8L49gFnDUEmupE2wLUMJzVFOumHhTks5qRFEegaJpZM4JBjx0>
> .
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by josemdv** [comment]
[DEFAULT]
activity_max_results = 100
auto_batch_min = 0
batch_size = 100
cache_dir = C:\Users\NASA\jma\.gam\gamcache
charset = mbcs
client_secrets_json = client_secrets.json
config_dir = C:\Users\NASA\jma\.gam
contact_max_results = 100
customer_id = my_customer
debug_level = 0
device_max_results = 500
domain = 
drive_dir = C:\Users\jma\Downloads
drive_max_results = 1000
extra_args = 
no_browser = true
no_cache = false
no_update_check = false
no_verify_ssl = false
num_threads = 20
oauth2_txt = oauth2.txt
oauth2service_json = oauth2service.json
section = 
show_counts_min = 1
show_gettings = true
user_max_results = 500

**Comment by taers232c** [comment]
I would set no_cache=true, no_update_check=true
Look in cache_dir, how much stuff is in there? I've never quite figured out
where gam caching gets you any benefit.

I have a user in Madrid who runs the Python version on his Windows server
rather than the EXE version and gets better performance.
gam.exe is a self extracting archive, 5000 extracts isn't cheap.

It does require having Python explicitly installed on the PC.

Ross

On Thu, Jun 30, 2016 at 4:42 PM, Ross Scroggs <ross.scroggs@gmail.com>
wrote:

> What values do you have for num_threads, no_cache and no_update_check?
>
> On Thu, Jun 30, 2016 at 4:28 PM, Just my stuff <notifications@github.com>
> wrote:
>
>> Thank you! Maybe this isn't related at all with this issue, but I found
>> that increasing the number of batch runs from 10 to 20, doesn't have any
>> effect. Running a query (delete a contact) for + 5K users is really time
>> consuming. It takes up to one hour. I have to delete up to 20 contacts
>> every day from all Google accounts. I tried also running several instance
>> of GAM at the same time but there is some type of PID lock that doesn't let
>> me run more than 2 instances at the same time.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229816916>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AIU8L49gFnDUEmupE2wLUMJzVFOumHhTks5qRFEegaJpZM4JBjx0>
>> .
>>
>
>
>
> --
> Ross Scroggs
> ross.scroggs@gmail.com
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Here are the basic steps to try the gam.py version.
Go here: https://www.python.org/downloads/release/python-2712/
Download the appropriate version x86 or x86-64 and install for all users;
chose to install full package.
Go here: https://github.com/taers232c/GAMADV-X/releases/tag/v4.17.1
Download the Source code (zip)
Make a new folder, I'll call it GAM4.
Open the zip file and put everything in src into GAM4
cd to GAM4
python gam.py  blah blah

In fact, you can put everything in src into the same folder as gam.exe,
there are no conflicts.

On Thu, Jun 30, 2016 at 4:49 PM, Ross Scroggs <ross.scroggs@gmail.com>
wrote:

> I would set no_cache=true, no_update_check=true
> Look in cache_dir, how much stuff is in there? I've never quite figured
> out where gam caching gets you any benefit.
>
> I have a user in Madrid who runs the Python version on his Windows server
> rather than the EXE version and gets better performance.
> gam.exe is a self extracting archive, 5000 extracts isn't cheap.
>
> It does require having Python explicitly installed on the PC.
>
> Ross
>
> On Thu, Jun 30, 2016 at 4:42 PM, Ross Scroggs <ross.scroggs@gmail.com>
> wrote:
>
>> What values do you have for num_threads, no_cache and no_update_check?
>>
>> On Thu, Jun 30, 2016 at 4:28 PM, Just my stuff <notifications@github.com>
>> wrote:
>>
>>> Thank you! Maybe this isn't related at all with this issue, but I found
>>> that increasing the number of batch runs from 10 to 20, doesn't have any
>>> effect. Running a query (delete a contact) for + 5K users is really time
>>> consuming. It takes up to one hour. I have to delete up to 20 contacts
>>> every day from all Google accounts. I tried also running several instance
>>> of GAM at the same time but there is some type of PID lock that doesn't let
>>> me run more than 2 instances at the same time.
>>>
>>> —
>>> You are receiving this because you commented.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/taers232c/GAMADV-X/issues/1#issuecomment-229816916>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe/AIU8L49gFnDUEmupE2wLUMJzVFOumHhTks5qRFEegaJpZM4JBjx0>
>>> .
>>>
>>
>>
>>
>> --
>> Ross Scroggs
>> ross.scroggs@gmail.com
>>
>
>
>
> --
> Ross Scroggs
> ross.scroggs@gmail.com
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by josemdv** [comment]
I'll give it a try!

Thanks for all your suggestion. I'll go ahead and close this issue!

Jose

**Comment by taers232c** [comment]
Another thought.
Are you saying: gam all users info contact query xxx
If so, you're not getting any parallelism because auto_batch_min=0
say: gam config auto_batch_min 1 all users info contact query xxx
Now gam will start num_threads and you'll get the parallelism you want.

If you are saying: gam cvs users.csv gam user "~User" info contact info
contact query xxx
then you are getting the parallelism.

Ross

On Thu, Jun 30, 2016 at 5:47 PM, Just my stuff <notifications@github.com>
wrote:

> Closed #1 <https://github.com/taers232c/GAMADV-X/issues/1>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/taers232c/GAMADV-X/issues/1#event-709931548>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AIU8L90mhwXeIr-VWuGl2ukUcqYj8Ji3ks5qRGOogaJpZM4JBjx0>
> .
>



-- 
Ross Scroggs
ross.scroggs@gmail.com
