### ISSUE TITLE
How to work with Gdrive

### ISSUE THREAD

**Issue by reivaj01** [taers232c/GAMADV-X#10]
Hello,

I'm trying to store all shared contacts in a spreadsheet.

My commands are:

gam print contacts todrive
gam print contacts todrive tdtitle directory
gam print contacts todrive tdtitle "directory"
gam print contacts todrive tdtitle directory tdparent id:0B2WQQKKi0TlTLVo3V2Ztdk9nVTg
gam print contacts todrive tdtitle "directory" tdparent id:0B2WQQKKi0TlTLVo3V2Ztdk9nVTg
gam print contacts todrive tdtitle directory tdparent Customers
gam print contacts todrive tdtitle "directory" tdparent "Customers"

But the spreadsheet is never create, the results only is showed in the screen.

Any suggestion?

Thanks and regards

**Comment by taers232c** [comment]
I apologize, I broke todrive, it doesn't work for any command. I'll fix it this morning.

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Fixed: https://github.com/taers232c/GAMADV-X/releases
--
ross.scroggs@gmail.com

**Comment by reivaj01** [comment]
Thank you very much,

Now everything works perfectly.

You're number one, the master of GitHub.

Thanks again
