### ISSUE TITLE
"collect orphans" - finds files that are "shared with me"

### ISSUE THREAD

**Issue by lerklompen** [taers232c/GAMADV-X#14]
(Nice implementation for finding orphaned files - thanks!)

"collect orphans" seems to find a lot of files that are "shared with me" but not added to "My Drive", i.e. files that aren't owned but somehow got shared with the user (directly/personally or through sharing with a group that the user is a member of).

We have quite a large domain with many groups. And many of the files that users find under "Shared with me" are not always necessarily relevant for them (and need not be added to the users Drive).

When I ran a preview I found that many of the "orphaned files" were actually not "owned by me", it would be nice to have a switch to enable the command to exclude "shared with me", or more correctly only files that are "owned by me" but has zero parents.

Regards
Mattias

**Comment by taers232c** [comment]
Mattias,

Thank you; more correctly only files that are "owned by me" but has zero parents now implemented.

Please test and let me know the results,

Ross

**Comment by lerklompen** [comment]
Yes it seems correct now.

Thanks!
/Mattias
