### ISSUE TITLE
gamx ignores the nobrowser.txt in Terminal on OSX 10.11.6

### ISSUE THREAD

**Issue by NoSubstitute** [taers232c/GAMADV-X#2]
Of course, it could be me, but I did put the nobrowser.txt file in a number of places and they were all ignored.
.gam
/Users/Kim (where I am when I run the command)
/Users/Kim/Documents/GAMADV-X-master/src/

Using alias to reach gam

alias gamx='/Users/Kim/Documents/GAMADV-X-master/src/gam.py'

Doing
./gam.py oauth create
inside the /Users/Kim/Documents/GAMADV-X-master/src/ dir also auto-loads a browser window.

**Comment by taers232c** [comment]
Kim,

GAMADV-X ignores all environment variables and signal files except GAMCFGDIR. That's what the gam.cfg configuration file is for.
By default gam.cfg is in ~/.gam, in your case, /Users/Kim/.gam.
If you want gam.cfg somewhere else, set GAMCFGDIR to the directory you'd like.
To see the current settings: gamx config verify
Want something different, edit gam.cfg.

The file GamConfig.txt gives the details.

Ross
--
ross.scroggs@gmail.com
