### ISSUE TITLE
Guide to GAM editions

### ISSUE THREAD

**Issue by beorn** [taers232c/GAMADV-X#21]
Hi, there are several versions of GAM available, and not too much guidance regarding which version to use.  I think this is hurting adoption of GAM - it certainly made me rather worried - e.g., should I use the -TD version since I want support for TD?  Or is that an experimental fork that's incomplete and should be avoided at all cost?  What's the long-term plan for these versions?

Would it be possible to have a wiki page that all GAM editions could link to, or at least the ones you make, that explains the different versions and the status that they are in, which versions you recommend people use, and which you might want help with?

(A bit related to #16)

**Comment by taers232c** [comment]
Bjorn,

GAM - a fork of Jay's version I use for submitting changes to him.
GAM-B - an improvement on GAM, but functionally the same.
GAMADV-X - a complete rewrite of GAM, uses Google Drive REST v2
GAMADV-XTD - GAMADV-X with Team Drive support, uses Google Drive REST v3
GAMADV-X3 - GAMADV-XTD converted to Python 3, source only, do not use unless you need Python 3 support

Ross

--
ross.scroggs@gmail.com
