### ISSUE TITLE
Collecting orphans fails (for many orphans)

### ISSUE THREAD

**Issue by beorn** [taers232c/GAMADV-X#23]
Hi,

I've probably got 200,000+ orphan files that I'd like to collect (and maybe delete), but depending on which machine I run it on, the job fails after 100,000 to 200,000 files, probably due to running out of memory.

I'd like to just get rid of these orphan files.  Any ideas?

```bash
gam select mydomain user myuser collect orphans
```
```
[...]
Got 145820 Drive Files/Folders for User: bjorn@stabell.org...
Got 145958 Drive Files/Folders for User: bjorn@stabell.org...
User: bjorn@stabell.org, Collect 0 Drive Orphan Files/Folders into Drive Folder: bjorn@stabell.org orphaned files
```

**Comment by taers232c** [comment]
Bjorn,

Is there an error message?
How do you get 200,000+ orphans? All files have a parent originally, to become an orphan its parent had to be deleted.

Ross
--
ross.scroggs@gmail.com

**Comment by beorn** [comment]
No error messages, and I got 200,000+ orphans as I inherited all files from a (now defunct) 100-employee company - I’m trying to archive things properly, and find some old docs that I need.

**Comment by taers232c** [comment]
Bjorn,

GAM downloads all the files and outputs all files with no parents. How did the 200,000+ files get to have no parents?
Is there no file structure at all, no folders? If you know the name of any of the files do the following:
gam select mydomain user myuser show filepath anydrivefilename "Put name nere"

What do you get?

Ross
--
ross.scroggs@gmail.com

**Comment by beorn** [comment]
I don't know which documents `collect orphans` tries to collect since it never completes.

What I can tell you is that https://drive.google.com/drive/search?q=is:unorganized shows only a handful of documents, but prompts to see other matching documents in the trash.  When I try https://drive.google.com/drive/trash does look to be very slow and seem to have an awful amount of documents (I didn't try to scroll through all of it).

So perhaps it's just my trash that is incredibly huge?  I have done a lot of deletion recently.  Does `collect orphans` also look for orphans in the trash?

**Comment by taers232c** [comment]
Bjorn,

Gam uses the query "'me' in owners and trashed = false" then looks through that list for files with no parents.
Interestingly, the query "is:unorganized" is not valid in the API.
$ gam user testuser1 print filelist fullquery "is:unorganized"
Getting all Drive Files/Folders that match query (is:unorganized) for testuser1@rdschool.org
User: testuser1@rdschool.org, Drive File Print Failed: Query (is:unorganized) Invalid
Owner,title,alternateLink

Take any of the files that you found with https://drive.google.com/drive/search?q=is:unorganized <https://drive.google.com/drive/search?q=is:unorganized> (call it xxx)
and do: gam user bjorn@stabell.org <mailto:bjorn@stabell.org> show fileinfo drivefilename "xxx"
What is under parents:


What do you mean, didn't complete?

Your example shows that Gam found no orphans, do you mean that it never returned to the prompt after the "User: bjorn@stabell.org <mailto:bjorn@stabell.org>, Collect 0 Drive Orphan Files/Folders into Drive Folder: bjorn@stabell.org <mailto:bjorn@stabell.org> orphaned files" line?
[...]
Got 145820 Drive Files/Folders for User: bjorn@stabell.org <mailto:bjorn@stabell.org>...
Got 145958 Drive Files/Folders for User: bjorn@stabell.org <mailto:bjorn@stabell.org>...
User: bjorn@stabell.org <mailto:bjorn@stabell.org>, Collect 0 Drive Orphan Files/Folders into Drive Folder: bjorn@stabell.org <mailto:bjorn@stabell.org> orphaned files
Ross
--
ross.scroggs@gmail.com

**Comment by beorn** [comment]
> On 20 Oct 2017, at 12:23 , Ross Scroggs <notifications@github.com> wrote:
> Gam uses the query "'me' in owners and trashed = false" then looks through that list for files with no parents.
> Interestingly, the query "is:unorganized" is not valid in the API.
> $ gam user testuser1 print filelist fullquery "is:unorganized"
> Getting all Drive Files/Folders that match query (is:unorganized) for testuser1@rdschool.org
> User: testuser1@rdschool.org, Drive File Print Failed: Query (is:unorganized) Invalid
> Owner,title,alternateLink
> 
> Take any of the files that you found with https://drive.google.com/drive/search?q=is:unorganized <https://drive.google.com/drive/search?q=is:unorganized> (call it xxx)
> and do: gam user bjorn@stabell.org <mailto:bjorn@stabell.org> show fileinfo drivefilename "xxx"
> What is under parents:

It seems all of the files under is:unorganized are not owned by me, and the query of that command seems to specify that user=me.

> What do you mean, didn't complete?
> 
> Your example shows that Gam found no orphans, do you mean that it never returned to the prompt after the "User: bjorn@stabell.org <mailto:bjorn@stabell.org>, Collect 0 Drive Orphan Files/Folders into Drive Folder: bjorn@stabell.org <mailto:bjorn@stabell.org> orphaned files" line?
> [...]
> Got 145820 Drive Files/Folders for User: bjorn@stabell.org <mailto:bjorn@stabell.org>...
> Got 145958 Drive Files/Folders for User: bjorn@stabell.org <mailto:bjorn@stabell.org>...
> User: bjorn@stabell.org <mailto:bjorn@stabell.org>, Collect 0 Drive Orphan Files/Folders into Drive Folder: bjorn@stabell.org <mailto:bjorn@stabell.org> orphaned files

Hm, the command “completed” but it didn’t say it collected any orphaned files.  How long it runs before it “completes” this way seems to vary by which machine I run it on, so I figured that it somehow ran into problems and just stopped.
