### ISSUE TITLE
Possible error in the syntax examples

### ISSUE THREAD

**Issue by horshacktest** [taers232c/GAMADV-X#26]
On this page in the wiki: https://github.com/taers232c/GAMADV-X/wiki/Contacts

I have been trying to get these examples to work:

```
gam <UserTypeEntity> info gal <ContactEntity> [basic|full] [fields <ContactFieldNameList>]
gam <UserTypeEntity> show gal [query <QueryContact>] [emailmatchpattern <RegularExpression>] [emailmatchtype work|home|other|<String>] [updated_min <Date>]
        [basic|full] [orderby <ContactOrderByFieldName> [ascending|descending]] [fields <ContactFieldNameList>]
gam <UserTypeEntity> print gal [todrive [<ToDriveAttributes>]] [query <QueryContact>] [emailmatchpattern <RegularExpression>] [emailmatchtype work|home|other|<String>] [updated_min <Date>]
        [basic|full] [orderby <ContactOrderByFieldName> [ascending|descending]] [fields <ContactFieldNameList>]
```

when I use the simple form `gam info gal p.XXXXXXXXXX` I get a sensible response. When I include a `<UserTypeEntity>` like `user jeff@mydomain.com` it throws the error:

```
ERROR: Invalid argument: Expected <asps|backupcodes|calendaracls|calendars|calsettings|contactgroups|contacts|delegates|driveactivity|drivefileacls|drivesettings|events|fileinfo|filelist|filepaths|filerevisions|filetree|filters|forward|forwardingaddresses|gmailprofile|gplusprofile|imap|labels|messages|pop|profile|sendas|sheetranges|signature|siteacls|sites|smimes|threads|tokens|vacation>
```

I think the examples may be incorrect. I'm not an expert in reading BNF but I interpret UserTypeEntity is required in the command.

**Comment by taers232c** [comment]
Jeff,

Corrected: <UserTypeEntity> should not be there.

Thanks,

Ross
--
ross.scroggs@gmail.com

**Comment by horshacktest** [comment]
Thanks Ross,

If I find something else would you prefer raising issues or a pull request on the wiki. I'm testing the examples to learn this vast tool.

--Jeff

**Comment by taers232c** [comment]
Jeff,

Just send me a direct email.

Thanks,

Ross
--
ross.scroggs@gmail.com
