### ISSUE TITLE
Incorrect "gam whatis" return codes

### ISSUE THREAD

**Issue by mfasen-wwf** [taers232c/GAMADV-X#27]
Link: https://github.com/taers232c/GAMADV-X/wiki/Aliases#determine-if-an-address-is-a-user-user-alias-group-or-group-alias

looking at return values from my test and also when looking at the source, the group and user alias values should be swapped:
User - 20
User Alias - 21
Group - 22
Group Alias - 23
Unknown - 59

I didn't see a way to edit the wiki, hence this post.

Keep up the excellent work!

Michel

**Comment by taers232c** [comment]
Michel,

You are correct, I've updated the Wiki.

Thanks you your help,

Ross
--
ross.scroggs@gmail.com
