### ISSUE TITLE
Underscore not allowed in site/URL

### ISSUE THREAD

**Issue by lerklompen** [taers232c/GAMADV-X#3]
Underscores in a site does not properly recompile as valid url:
"Site: pagy_elev_old, Not Deleted: Invalid Site (pagy_elev_old), must match pattern ([a-z,0-9,-]+)"

Works if underscore is added to this regex:
SITENAME_PATTERN = re.compile(r'^[a-z0-9\-_]+$')

Not needed but more correct error message:
SITENAME_FORMAT_REQUIRED = u'[a-z,0-9,-_]+'

Command now works as intended:
  Site: domain.com/pagy_elev_old, Delete 1 ACL (1/2)
    Site: domain.com/pagy_elev_old, ACL: (Scope: user:some.one@domain.com), Deleted

/Mattias

**Comment by lerklompen** [comment]
(the editor removes the backslash in the regex...)
SITENAME_PATTERN = re.compile(r'^[a-z0-9\\-_]+$')

**Comment by taers232c** [comment]
Mattias,

Thank you, I'll make change.

Ross
--
ross.scroggs@gmail.com
