### ISSUE TITLE
Bulk upload of folder contents to one user folder

### ISSUE THREAD

**Issue by rasqual** [taers232c/GAMADV-X#37]
I can tell it's a Monday, 'cause I can't figure this out.

I'm trying to upload all files in a single folder on Windows, to a specific user's folder on Drive.

The first variant indicated below is my immediate need, but the others would be handy. 

1. Target drive folder exists, over-write any existing files in target (no source content is subfoldered)
2. Same as (1), but rename uploads (prepend a string) where identical names exist in target
3. Target drive folder doesn't exist, create on Drive with same local name and all contents (including subfolders)
4. Be able to filter out particular extensions or mime types in variant (3)

I presume (1) would be a csv operation?

**Comment by taers232c** [comment]
This would be a very large undertaking, others reports success with: https://rclone.org/
