### ISSUE TITLE
Getting error 'Client OAuth2 File ... Does not exist or has invalid format"

### ISSUE THREAD

**Issue by phillipalexander** [taers232c/GAMADV-X#4]
I couldn't get GAMADV-X to work using the linked installation/config instructions for jay0lee/GAM found [here](https://github.com/jay0lee/GAM/wiki#mac-and-linux-users-2), so instead, I tried getting jay0lee/GAM working (which I was able to do) and then used the OLDGAMPATH environmental variable as described in [GAMCONFIG.txt](https://github.com/taers232c/GAMADV-X/blob/master/src/GamConfig.txt#L49-L53) to setup GAMADV-X, but I'm still getting the following error:

```
Created: /Users/phillipalexander/.gam
Created: /Users/phillipalexander/.gam/gamcache
Copied: /Users/phillipalexander/src/github.com/_misc/GAM/src/oauth2service.json, To: /Users/phillipalexander/.gam/oauth2service.json
Copied: /Users/phillipalexander/src/github.com/_misc/GAM/src/client_secrets.json, To: /Users/phillipalexander/.gam/client_secrets.json
Copied: /Users/phillipalexander/src/github.com/_misc/GAM/src/oauth2.txt, To: /Users/phillipalexander/.gam/oauth2.txt
Config File: /Users/phillipalexander/.gam/gam.cfg, Initialized

ERROR: Client OAuth2 File: /Users/phillipalexander/.gam/oauth2.txt Does not exist or has invalid format
```

I've verified that the OAuth2.txt file exists and I'm not sure why it isn't working. Any ideas would be greatly appreciated!

**Comment by taers232c** [comment]
Phillip,

I'm assuming that since you closed the issue you found that you need to do:
gam oauth delete
gam oauth create
Let me know if you need any additional assistance.

Ross
