### ISSUE TITLE
gamadv-x Attachment compliance

### ISSUE THREAD

**Issue by manassahoo10** [taers232c/GAMADV-X#40]
Hi All,
 Which command i bypass email ID in google mail Attachment compliance

Thanks
Manas

**Comment by taers232c** [comment]
Manas,

Questions like this should be addressed to: google-apps-manager@googlegroups.com as there are more people able to answer the question. I don't understand the question, what are you trying to achieve?

Ross

**Comment by manassahoo10** [comment]
Hi Ross,
Thanks for the reply. I want know which command in gamadv-x  we configure attachment complience in google admin.

Thanks
Manas

**Comment by taers232c** [comment]
Manas,

There is no API support for managing Admin Console/Apps/G Suite settings, thus Gam can not configure these settings.

Ross
--
ross.scroggs@gmail.com
