### ISSUE TITLE
ERROR: Missing argument: Expected <ACLScopeEntity>

### ISSUE THREAD

**Issue by jaredneedell** [taers232c/GAMADV-X#43]
Can you give me an example of what ACLScopeEntities are?

I'm trying to get all permissions for a resource calendar.

**Comment by taers232c** [comment]
Jared,

<CalendarACLScope> ::= <EmailAddress>|user:<EmailAddress>|group:<EmailAddress>|domain:<DomainName>)|domain|default
<CalendarACLScopeList> ::= "<CalendarACLScope>(,<CalendarACLScope>)*"
<CalendarACLScopeEntity>::= <CalendarACLScopeList> | <FileSelector> | <CSVkmdSelector> | <CSVDataSelector>

Simple: user:tom@domain.com <http://domain.com/>
List: user:dick@domain.com <http://domain.com/>,group:sales@domain.com <http://domain.com/>

Suppose you want to copy ACLS from one resource calendar to another:
gam resources <OldResourceId> print calendaracls > ResourceAcls.csv
This gives you headers: resourceId,resourceEmail,id,role,scope.type,scope.value
gam csv ResourceAcls.csv gam resources <NewResoureID> add calendaracls ~scope.type ~scope.value

Ross
--
ross.scroggs@gmail.com
