### ISSUE TITLE
claim ownership - "filepath" missing in declaration

### ISSUE THREAD

**Issue by lerklompen** [taers232c/GAMADV-X#5]
When trying to run "claim ownership" without "filepath" GAM crashes.

"filepath" is missing in the declaration below:
csvFormat = trashed = filepath = False

----
Traceback (most recent call last):
  File "gam.py", line 24017, in ProcessGAMCommand
    USER_COMMANDS_WITH_OBJECTS[CL_command][CMD_FUNCTION][CL_objectName](entityList)
  File "gam.py", line 19205, in claimDriveFolderOwnership
    if filepath:
UnboundLocalError: local variable 'filepath' referenced before assignment
----

//Mattias

**Comment by taers232c** [comment]
Thank you
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Fixed: https://github.com/taers232c/GAMADV-X/releases/tag/v4.33.01
