### ISSUE TITLE
missing subgroup as filter for fields

### ISSUE THREAD

**Issue by Megachip** [taers232c/GAMADV-X#55]
see subject ;)

Thanks a lot

**Comment by taers232c** [comment]
I'm not clear on the problem; what command are you trying to execute?

**Comment by taers232c** [comment]
I need additional info, please let me know what you're trying to do and I'll respond.

**Comment by taers232c** [comment]
I'm closing this issue for now; if you have additional information to help me understand what you need, please start a new issue.

Ross

**Comment by Megachip** [comment]
Example:
`gam print group-members group team-berlin notsuspended recursive fields "email,role,subgroup"`

field subgroup is not known in that case
