### ISSUE TITLE
GamConfig.txt missing

### ISSUE THREAD

**Issue by frankwaltz** [taers232c/GAMADV-X#58]
README.md says to read GamConfig.txt in a few places. There is no such file on a fresh install. Maybe not at all? It doesn't seem to be necessary since I was able to complete the configuration without finding or reading such file.

**Comment by taers232c** [comment]
Frank,

The local file GamConfig.txt has been deleted, here is the information: https://github.com/taers232c/GAMADV-X/wiki/gam.cfg <https://github.com/taers232c/GAMADV-X/wiki/gam.cfg>

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Frank,

References fixed, thanks for pointing this out.

Ross
