### ISSUE TITLE
License count total available vs used.

### ISSUE THREAD

**Issue by daniejstriata** [taers232c/GAMADV-X#61]
Hi,

When I query licenses for my instance of G Suite I see 300 but I want to know how many licenses I have available so I can request more when I reach the max. I can see that by visiting  **Manage licenses** under billing where I'll see:

Current Licenses | G Suite Business | 300/305 licenses used

**gam show licenses countsonly**
```
Got 0 Licenses for 101001...
Got 0 Licenses for 101005...
Got 0 Licenses for 101031...
Got 152 Licenses for Google-Apps...
Got 0 Licenses for Google-Chrome-Device-Management...
Got 0 Licenses for Google-Coordinate...
Got 0 Licenses for Google-Drive-storage...
Got 0 Licenses for Google-Vault...
Product: 101001 (Cloud Identity), Licenses: 0
Product: 101005 (Cloud Identity Premium), Licenses: 0
Product: 101031 (G Suite Enterprise for Education), Licenses: 0
Product: Google-Apps (G Suite), Licenses: 300
Product: Google-Chrome-Device-Management (Google Chrome Device Management), Licenses: 0
Product: Google-Coordinate (Google Coordinate), Licenses: 0
Product: Google-Drive-storage (Google Drive storage), Licenses: 0
Product: Google-Vault (Google Vault), Licenses: 0
```
I had a similar question on the GAM board a while ago:
https://github.com/jay0lee/GAM/issues/507

**Comment by taers232c** [comment]
The Licensing API doesn't return the total licenses, just the used licenses.
Try: gam info customer
It uses the Reports API that does have the information.

Ross
--
ross.scroggs@gmail.com
