### ISSUE TITLE
Error when executing "gam show group-members group groupname@domain.com"

### ISSUE THREAD

**Issue by joetjef** [taers232c/GAMADV-X#66]
When I run the command "gam show group-members group groupname@domain.com" I get the following error:

Group: groupname@domain.com
Traceback (most recent call last):
  File "/usr/local/gamadv-x/gam", line 36755, in ProcessGAMCommand
    MAIN_COMMANDS_WITH_OBJECTS[CL_command][CMD_FUNCTION][CL_objectName]()
  File "/usr/local/gamadv-x/gam", line 15010, in doShowGroupMembers
    _showGroup(groupEmail, 0)
  File "/usr/local/gamadv-x/gam", line 14930, in _showGroup
    for member in sorted(membersList, key=lambda k: (_roleOrder(k.get(u'role', Ent.ROLE_MEMBER)), _typeOrder(k[u'type']), _statusOrder(k['status']))):
  File "/usr/local/gamadv-x/gam", line 14930, in <lambda>
    for member in sorted(membersList, key=lambda k: (_roleOrder(k.get(u'role', Ent.ROLE_MEMBER)), _typeOrder(k[u'type']), _statusOrder(k['status']))):
KeyError: 'status'

The command "gam print group-members group groupname@domain.com" is working fine however (ie print (CSV format) instead of show (hierarchical format)). I've tried a few groups and they all show the same error.

I'm using the latest GAM version:
GAM 4.65.30 - https://github.com/taers232c/GAMADV-X
Ross Scroggs <ross.scroggs@gmail.com>
Python 2.7.15 64-bit final
google-api-python-client 1.7.4
httplib2 0.12.0
auth2client 4.1.3
Linux-4.14.77-70.59.amzn1.x86_64-x86_64-with-glibc2.2.5 x86_64
Path: /usr/local/gamadv-x/src

**Comment by taers232c** [comment]
Will fix shortly

**Comment by taers232c** [comment]
Fixed in 4.65.31. Thanks for notifying me about the error.

Ross

**Comment by taers232c** [comment]
I'll post corrected version later this morning.
--
ross.scroggs@gmail.com
