### ISSUE TITLE
GAMADV-X not handling ERROR 600

### ISSUE THREAD

**Issue by josemdv** [taers232c/GAMADV-X#67]
Command:

gam all users print contact query "test@domain.com".

I'm running multiple threads querying contacts for all users and I noticed that GAMADV-X isn't handling properly the error:

`
Getting all Contacts that match query (contactuser1@domain.com) for user4554@domain.com (4554/6355)
`
`Got 0 Contacts...`
`Getting all Contacts that match query (contactuser1@domain.com) for user4555@domain.com (4555/6355)`
`ERROR: 600 - Unknown Error: {'status': 504, 'body': 'Deadline exceeded.', 'reason': 'Gateway Timeout'}`
`Getting all Contacts that match query (contactuser2@domain.com) for user1@domain.com (1/6355)`
`Got 0 Contacts...`
`Getting all Contacts that match query (contactuser2@domain.com) for user2@domain.com (2/6355)`
`Got 0 Contacts...`

When that error happens, it doesn't retry nor continues , it just dies and continues to the next contact search. I'd expect to continue with the next user in line.

Please note that when this happens, the rest of the threads continue working fine (and they don't have issues with the gateway).

**Comment by taers232c** [comment]
Handled in 4.65.33

**Comment by josemdv** [comment]
You are the best! It works now
