### ISSUE TITLE
Building GAMADV-X on Mac OS X

### ISSUE THREAD

**Issue by lerklompen** [taers232c/GAMADV-X#7]
I can build GAM on Mac but get this file with warnings in the build directory. See attached files with output from build, and file with warnings.
[warnmacos-gam.txt](https://github.com/taers232c/GAMADV-X/files/633320/warnmacos-gam.txt)
[output.txt](https://github.com/taers232c/GAMADV-X/files/633322/output.txt)

The binary is smaller in size (6,1 MB vs yours on 7,1 MB).

The binary seems to work though, but always adds this line after the command is ready:
"Failed to execute script gam"

I only have the standard or "preinstalled" python version 2.7.10, and then pyinstaller installed via "pip".

Also i have to change this line in the build script:
"/Library/Frameworks/Python.framework/Versions/2.7/bin/pyinstaller ..."
to
"pyinstaller ..."
It seems that pip installs PyInstaller in /usr/local/bin/ so it is possible to run it without adding the path.

There seems to be no difference if I build with "sudo" or not (I don't know which is recommended though).

Are there any other requirements or "special" versions I should be aware of? Do I need Xcode setup on my system for instance?

I have tried this on both Mac OS Sierra and Yosemite with the same result.

/Mattias

**Comment by taers232c** [comment]
Mattias,


You have to dowload the pyinstaller source and rebuild the bootloader. Here's what I did:
1) Download source into some directory
2) sudo su -
3) cd /
4) mkdir /SourceCache  (This is where I keep all of my 3rd party source)
5) mv /SomeDirectory/PyInstaller-3.2.tar.gz .
6) tar -xzvf PyInstaller-3.2.tar.gz
7) rm PyInstaller-3.2.tar.gz
8) cd PyInstaller-3.2/bootloader/
9) python ./waf distclean all
10) cd ..
11) python setup.py install
12) exit

This leaves pyinstaller in /Library/Frameworks/Python.framework/Versions/2.7/bin/

Ross
--
ross.scroggs@gmail.com

**Comment by lerklompen** [comment]
(step "5" should be "cd /SourceCache")

Thanks for clearing things out reguarding rebuilding the bootloader. Though it seems that "pip" might be able to do this also according to this:
https://pythonhosted.org/PyInstaller/bootloader-building.html

But it seems one have to install Xcode and do an initial run, otherwise "python ./waf distclean all" can't find any C compiler (and maybe "pip" would be able to build the proper bootladers also?).

I'll report back if the macos-build works better after this...

Thanks
Mattias

**Comment by lerklompen** [comment]
Ok, seems one have to do the "python ./waf distclean all" and install pyinstaller manually according to your steps. 

However both on Sierra and Yosemite my pyinstaller ends up in "/usr/local/bin/" so I still have to change in "macos-build.sh":
"/Library/Frameworks/Python.framework/Versions/2.7/bin/pyinstaller ..."
to
"pyinstaller ..."
 
But the file size is similarly smaller as before (only 4 k bigger), and the warnings file seem to contain kind of the same warnings. But maybe there is something else differing in our build environments that would cause this?

The binary seems to work fine now, and I no longer get the "Failed to execute script gam".

Thanks
Mattias

**Comment by taers232c** [comment]
Mattias,

What's the status of this issue?

Ross

**Comment by lerklompen** [comment]
Everything builds fine now it seems (though the binary size differs, this might depend on exactly what system/computer you have as I understand).

I had to take these steps to be able to get a working binary:
1. Install Xcode.
After installing Xcode (one also needs to open Xcode for an initial run, this seems to trigger things).

2. Rebuild the bootloader and install pyinstaller according to your instructions.

3. Edit "macos-build.sh"
One might need to edit (or remove) the path to pyinstaller in this script:
pyinstaller [...]

/Mattias
