### ISSUE TITLE
print groups where email macthes

### ISSUE THREAD

**Issue by jbanner6736** [taers232c/GAMADV-X#71]
I have been trying ot print groups whose email address matches \-s.* which is a python regex and should match group-s1@domain.com but it is not working :(

How do you only print or to csv where the group email address contains?

**Comment by taers232c** [comment]
Please show the command you are executing.

Ross
--
ross.scroggs@gmail.com

**Comment by jbanner6736** [comment]
gam print groups settings emailmatchpattern [-s.*]

**Comment by jbanner6736** [comment]
also tried gam print groups settings emailmatchpattern -s.*

**Comment by taers232c** [comment]
Is this resolved?

**Comment by taers232c** [comment]
I'm closing this for now as I've gotten no response; if you still have an issue, email me directly at ross.scroggs@gmail.com.
