### ISSUE TITLE
ERROR: 600 - Unknown Error: {'status': 403, - when trying to add global contact

### ISSUE THREAD

**Issue by Barnnzi** [taers232c/GAMADV-X#75]
Hi, I love what you've done with this.  Thank you.  

Could you take a look at this error and advise?  Thanks!

gam create contact firstname Jim familyname Jones email work Jim.Jones@somedomain.com primary

ERROR: 600 - Unknown Error: {'status': 403, 'body': '<HTML>\n<HEAD>\n<TITLE>Cannot request contacts belonging to another domain (domain.com).</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Cannot request contacts belonging to another domain (domain.com).</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n', 'reason': 'Cannot request contacts belonging to another domain (domain.com).'}

**Comment by taers232c** [comment]
I can't reproduce, call you call me on Google Hangouts.

ross.scroggs@gmail.com

**Comment by Barnnzi** [comment]
Thanks for the quick response.  Feel free to try calling me back if you're available in the next couple of hours.
