### ISSUE TITLE
Duplicate "aliases" column name when printing courses.

### ISSUE THREAD

**Issue by ShaunDarkLord** [taers232c/GAMADV-X#76]
Hi

When executing "gam.exe print courses state provisioned state active state declined alias fields id fields name fields courseState owneremail > file.csv" two "Aliases" columns are created;

id,name,Aliases,courseState,ownerEmail,ownerId,Aliases
368#########,Test,tws_test,ACTIVE,me@mydomain.com,1009###########,tws_test

This creates an issue for me when trying to import this csv into a script, as Powershell doesn't like duplicate csv headers.

**Comment by taers232c** [comment]
Fixed 4.83.02.

I suggest upgrading to GAMADV-XTD3 as it is the only version that will be enhanced in the future.
All versions will get bug fixes.

**Comment by ShaunDarkLord** [comment]
Perfect - Thank you.

Have upgraded and all working perfectly.
