### ISSUE TITLE
Issue when deleting contacts of an email

### ISSUE THREAD

**Issue by NaoueleK** [taers232c/GAMADV-X#77]
Could you please fix this issue on gamadv-x?
We need to cleanup contacts asap for several end users.

Our need:
We need to delete from users G Suite contacts some email addresses based on domain names, for example : gs.example.com, emea.example.com .
Knowing that we need to keep the contacts themselves and to keep the other email addresses for other domains. 

For example if we had the contact :
contact@example.com
contact@gs.example.com
contact@emea.example.com
contact.emea@example.com
contact.alias@otherdomain.com

We need to have at the end only 3 addresses:
contact@example.com
contact.emea@example.com
contact.alias@otherdomain.com

The issue:
The issue is that we tested using the following command:
gam user XXX clear contacts emailmatchpattern "(?i).*@(gs.example.com|emea.example.com)"

At first, we thought it was ok because the email addresses disappeared.
Then we realized that gamadv-x kept an entry for the removed addresses and duplicated one of the kept one, very confusing.

The result we unfortunately have with above sample is:
contact@example.com
contact@example.com
contact@example.com
contact.emea@example.com
contact.alias@otherdomain.com

The two addresses are not removed but replaced by the first kept one.

Knowing that you do not see it when you look at the contact in G Suite in read mode in contacts.google.com but only 1) in edit mode or 2) when composing an email and look for a contact.
Could you please fix this?

![Untitled presentation](https://user-images.githubusercontent.com/52070058/59914771-573aa600-941b-11e9-9cf0-5c508f61c780.png)

**Comment by taers232c** [comment]
Was this one contact with five address or five separate contacts?
For example if we had the contact :
contact@example.com
contact@gs.example.com
contact@emea.example.com
contact.emea@example.com
contact.alias@otherdomain.com

At first, we thought it was ok because the email addresses disappeared.
Disappeared from where? Were you using Gam to look at the contacts?

Can you contact me on Google Hangouts? I'm in California (PDT)

ross.scroggs@gmail.com

**Comment by taers232c** [comment]
```
$ gam user testuser5 create contact email work contact@example.com primary email work contact@gs.example.com notprimary email work contact@emea.example.com notprimary email work contact.emea@example.com notprimary email work contact.alias@otherdomain\
.com notprimary
User: testuser5@domain.com, Contact: 35098ac68c1bd3ac, Created
$ gam user testuser5 show contacts
Getting all Contacts for testuser5@domain.com
Got 1 Contact...
User: testuser5@domain.com, Show maximum of 1 Contact
  Contact: 35098ac68c1bd3ac
    Updated: 2019-06-21T07:37:59-07:00
    Emails:
      type: work
        rank: primary
        address: contact@example.com
      type: work
        rank: notprimary
        address: contact@gs.example.com
      type: work
        rank: notprimary
        address: contact@emea.example.com
      type: work
        rank: notprimary
        address: contact.emea@example.com
      type: work
        rank: notprimary
        address: contact.alias@otherdomain.com
$ gam config debug_level 1  user testuser5 clear contacts emailmatchpattern "(?i).*@(gs.example.com|emea.example.com)"
  User: testuser5@domain.com, Contact: 35098ac68c1bd3ac, Updated
$ gam user testuser5 show contacts
Getting all Contacts for testuser5@domain.com
Got 1 Contact...
User: testuser5@domain.com, Show maximum of 1 Contact
  Contact: 35098ac68c1bd3ac
    Updated: 2019-06-21T07:39:10-07:00
    Emails:
      type: work
        rank: primary
        address: contact@example.com
      type: work
        rank: notprimary
        address: contact.emea@example.com
      type: work
        rank: notprimary
        address: contact.alias@otherdomain.com
$
```

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-X/wiki/GAM-Updates

Ross

**Comment by taers232c** [comment]
Naouele,

Call me at your convenience.

Ross
