### ISSUE TITLE
no_update_check broken?

### ISSUE THREAD

**Issue by lerklompen** [taers232c/GAMADV-X#8]
I have "no_update_check = true" in my gam.cfg, but GAMADV still does a version check.

/Mattias

**Comment by taers232c** [comment]
Mattias,

Thanks. Here's the change, but before making it please confirm something.
I'm testing an obsolete variable that is always False so doGAMCheckForUpdates is getting called.
But is Gam really checking or does lastupdatecheck.txt prevent the check?
Temporarily put in the print statement below; is 'check'  printed?

def doGAMCheckForUpdates(forceCheck=False):
  import urllib2
  import calendar

  current_version = __version__
  now_time = calendar.timegm(time.gmtime())
  if forceCheck:
    check_url = GAM_ALL_RELEASES # includes pre-releases                                                                                                                                                                                                                                           
  else:
    last_check_time_str = readFile(GM_Globals[GM_LAST_UPDATE_CHECK_TXT], continueOnError=True, displayError=False)
    last_check_time = int(last_check_time_str) if last_check_time_str and last_check_time_str.isdigit() else 0
    if last_check_time > now_time-604800:
      return
###                                                                                                                                                                                                                                                                                                
    print 'check'
    check_url = GAM_LATEST_RELEASE # latest full release                                                                                                                                                                                                                                           

Fix here:


In SetGlobalVariables, change:
  if not GM_Globals[GM_NO_UPDATE_CHECK]:
    doGAMCheckForUpdates()
to
  if not GC_Values[GC_NO_UPDATE_CHECK]:
    doGAMCheckForUpdates()

Ross
--
ross.scroggs@gmail.com



On Dec 21, 2016, at 10:43 PM, Mattias Bystedt <notifications@github.com> wrote:

> I have "no_update_check = true" in my gam.cfg, but GAMADV still does a version check.
> 
> /Mattias
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

**Comment by taers232c** [comment]
Fixed
