### ISSUE TITLE
Exception when using "print sheetrange"

### ISSUE THREAD

**Issue by joetjef** [taers232c/GAMADV-X#80]
Version: GAM 4.88.10 - https://github.com/taers232c/GAMADV-X
Command: gam user <user> print sheetrange <id> range A3:A4
Output: Traceback (most recent call last):
  File "/usr/local/gamadv-x/gam", line 39438, in ProcessGAMCommand
    USER_COMMANDS_WITH_OBJECTS[CL_command][CMD_FUNCTION][CL_objectName](entityList)
  File "/usr/local/gamadv-x/gam", line 34976, in printShowSheetRanges
    addRowTitlesToCSVfile(flattenJSON(result, flattened={'User': user, 'spreadsheetId': spreadsheetId}), csvRows, titles)
  File "/usr/local/gamadv-x/gam", line 5514, in flattenJSON
    for k, v in sorted(iteritems(topStructure)):
  File "/usr/local/gamadv-x/gam", line 124, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'

I've tried several (new and old) spreadsheets, the command "gam user <user> info sheet <id>" is working fine just like the "show sheetrange" command on the same spreadsheet.

Let me know if  you need any additional information

Joetje

**Comment by taers232c** [comment]
Joetje,

I can duplicate, I'll fix this morning.

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Fixed 4.89.00

**Comment by joetjef** [comment]
Just tested it and it works great, thanks for the always super quick support!

Joetje
