### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by rmo000** [taers232c/GAMADV-X#85]
During installation a link with the scope of apis is generated. Group scope is incomplete, generating invalid scope error.

**Comment by taers232c** [comment]
This is windows I assume.
Try this:
gam config no_browser true save
gam oauth create

What version of Windows are you on?

--
ross.scroggs@gmail.com

**Comment by rmo000** [comment]
It's a Windows 10 Home
I used these two commands but the error persists.

I was able to solve by adding the scope in the URL that is generated.
