### ISSUE TITLE
Invalid argument 'to' in 'move event' command

### ISSUE THREAD

**Issue by dsverdlo** [taers232c/GAMADV-X#91]
Hello,

In the documentation ([here](https://github.com/taers232c/GAMADV-X/wiki/Calendars-Events#move-calendar-events-to-another-calendar)) it is mentioned that one can move events like this:
`gam calendar <CalendarEntity> move event <EventEntity> to <CalendarItem> [notifyattendees]`

However, when I tried to do this, I got an ERROR: Invalid argument, and 'to' was syntax highlighted.

![image](https://user-images.githubusercontent.com/2640283/72354844-afeacc80-36e6-11ea-8796-b0ed3d9d8294.png)

Is this a bug or am I doing something wrong here?

Thanks for checking.
David

**Comment by taers232c** [comment]
David,

This version of GAM is no longer supported.
See: https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-GAMADV-X-or-GAMADV-XTD
However, it should work in your version, your command is slightly off.
Syntax:
```
<EventEntity> ::=
        (events <EventIdList> | <FileSelector> | <CSVkmdSelector> | <CSVSubkeySelector> | <CSVDataSelector>)|
        (<EventSelectProperties>+ <EventMatchProperties>*)
gam calendar|calendars <CalendarEntity> move events <EventEntity> to <CalendarItem> [notifyattendees]
```
Add `events` keyword:
```
gam calendar oldcalendar@domain.com move event events 40am...96d to newcalendar@domain.com
```

**Comment by dsverdlo** [comment]
Hello Ross,

Thanks for your quick reply and insights!
Modifying the command worked, I must have misread the Syntax documentation.

I'll do the upgrade later this week.
Br,
David
